version: 2
jobs:
  build:
    docker:
      - image: circleci/node:10.12
    working_directory: ~/repo
    steps:
      - checkout
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "package.json" }}
            - v1-dependencies-
      - run: yarn install
      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package.json" }}

  test:
    working_directory: ~/repo
    docker:
      - image: circleci/node:10.12
    steps:
      - checkout
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "package.json" }}
            - v1-dependencies-
      - run:
          name: Install dependencies
          command: yarn
      - run:
          name: Run test
          command: yarn ci:test
      - run:
          name: Report test coverage
          context: danger
          command: yarn ci:report

workflows:
  version: 2
  pull-request:
    jobs:
      - test
      - build:
          requires:
            - test
